version: '3.8'

services:
#  app:
#    image: php:8.1-fpm
#    container_name: laravel_app
#    working_dir: /var/www
#    volumes:
#      - ./:/var/www
#      - ./php.ini:/usr/local/etc/php/php.ini
#    networks:
#      - laravel

#  webserver:
#    image: nginx:alpine
#    container_name: laravel_webserver
#    working_dir: /var/www
#    volumes:
#      - ./:/var/www
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - "8000:80"
#    networks:
#      - laravel

  db:
    image: mysql:8
    platform: linux/x86_64
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel


  db_test:
    image: mysql:8
    platform: linux/x86_64
    container_name: laravel_db_test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_test:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
  db_test:
